apiVersion: v1
kind: Pod
metadata:
  name: licorice
spec:
  containers:
  - name: redis-client
    image: redis
  - name: ambassador
    image: alpine:1.2
    env:
    - name: clubpenguin-ambassador
      value: "Ambassador Design Pattern" 
    ports:
    - containerPort: 8080
